@startuml classes_monitoreo
set namespaceSeparator none
class "AppPasajero" as dominio.AppPasajero {
  pasajero
  servicio_monitoreo
  consultar_eta(paradero: Paradero) -> None
  mostrar_resultado(eta: Optional[int]) -> None
}
class "Bus" as dominio.Bus {
  capacidad : int
  id_bus : str
  placa : str
  ubicacion_actual : Optional[Coordenada]
  actualizar_ubicacion(coord: Coordenada) -> None
}
class "Coordenada" as dominio.Coordenada {
  latitud : float
  longitud : float
}
class "EstadoViaje" as dominio.EstadoViaje {
  name
}
class "INotificador" as dominio.INotificador {
  {abstract}notificar_retraso(viaje: 'Viaje') -> None
}
class "IProveedorGPS" as dominio.IProveedorGPS {
  {abstract}obtener_coordenada_actual(id_bus: str) -> Coordenada
}
class "IServicioMapas" as dominio.IServicioMapas {
  {abstract}calcular_eta(origen: Coordenada, destino: Coordenada) -> int
}
class "Paradero" as dominio.Paradero {
  id_paradero : str
  nombre : str
  ubicacion
  obtener_viajes_proximos() -> List['Viaje']
}
class "Pasajero" as dominio.Pasajero {
  id_pasajero : str
  ubicacion_actual
}
class "ProveedorGPSAdapter" as dominio.ProveedorGPSAdapter {
  {abstract}obtener_coordenada_actual(id_bus: str) -> Coordenada
}
class "Ruta" as dominio.Ruta {
  id_ruta : str
  nombre : str
  paraderos : List[Paradero]
  obtener_paraderos() -> List[Paradero]
}
class "ServicioMapasAdapter" as dominio.ServicioMapasAdapter {
  {abstract}calcular_eta(origen: Coordenada, destino: Coordenada) -> int
}
class "ServicioMonitoreoSIT" as dominio.ServicioMonitoreoSIT {
  notificador
  proveedor_gps
  procesar_alerta_desvio(viaje: Viaje) -> None
  solicitar_eta(pasajero: Pasajero, paradero: Paradero) -> Optional[int]
}
class "Viaje" as dominio.Viaje {
  bus
  estado
  hora_inicio_programada : datetime
  id_viaje : str
  servicio_mapas
  calcular_tiempo_llegada(destino: Paradero) -> Optional[int]
  cambiar_estado(nuevo_estado: EstadoViaje) -> None
  programar() -> None
  registrar_contingencia(motivo: str) -> None
}
class "WebPushAdapter" as dominio.WebPushAdapter {
  {abstract}notificar_retraso(viaje: 'Viaje') -> None
}
dominio.ProveedorGPSAdapter --|> dominio.IProveedorGPS
dominio.ServicioMapasAdapter --|> dominio.IServicioMapas
dominio.WebPushAdapter --|> dominio.INotificador
dominio.Viaje --> dominio.Bus : bus
dominio.Paradero --> dominio.Coordenada : ubicacion
dominio.Pasajero --> dominio.Coordenada : ubicacion_actual
dominio.Viaje --> dominio.EstadoViaje : estado
dominio.Viaje --> dominio.IServicioMapas : servicio_mapas
dominio.INotificador --o dominio.ServicioMonitoreoSIT : notificador
dominio.IProveedorGPS --o dominio.ServicioMonitoreoSIT : proveedor_gps
dominio.Pasajero --o dominio.AppPasajero : pasajero
dominio.ServicioMonitoreoSIT --o dominio.AppPasajero : servicio_monitoreo
@enduml
